### PR TITLE
Add github action

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

see #18 

This PR add GitHub actions.

### CODE REVIEW

**Comment by soroshsabz** [comment]
@splitice please review it

**Comment by soroshsabz** [comment]
Did you have any comment about this? :)

**Comment by soroshsabz** [comment]
@splitice

**Comment by splitice** [comment]
While I was able to get your actions workflow closer to working (see https://github.com/splitice/IPTables.Net/actions) there remains issues with getting the tests to pass in actions land. Likely due to the docker wrapper.

**Comment by soroshsabz** [comment]
Resolve segmentation fault in Ubuntu

I found IPv6 and filtered dump in Ubuntu 22.04 cause problem in your library

I write test for each of them in main.c (ipthelper/test) and you can see details problem

@splitice  I suggest to you approve this PR and resolve these bug in future

**Comment by soroshsabz** [comment]
All problem are for Ubuntu 22.04 that is created bug issue for that #25 

After I change os to Ubuntu 20.04 all of things is good and CI is green

@splitice So I think you can approve this PR

**Comment by soroshsabz** [comment]
@splitice if you have any note, please notify me ;)

**Comment by soroshsabz** [comment]
@splitice Is there any problem to does not merge this PR?

**Comment by splitice** [comment]
We can not choose to skip tests. Issues need to be diagnosed and fixed before any migration will proceed.

Currently I don't have the time for this.

It might be ipv6 related as you mentioned. Or it might be an API change/bug. Needs time.

**Comment by soroshsabz** [comment]
@splitice All test are passed, IPv6 and IPv6 passed both of them, no any test ignore (as you can see in PR)

As I previous say, the problem is for Ubuntu 22.04, and I chagne env to Ubuntu 20.04

This PR passed all tests

**Comment by soroshsabz** [comment]
@splitice All test are passed, IPv6 and IPv4 passed both of them, no any test ignore (as you can see in PR)

As I previous say, the problem is for Ubuntu 22.04, and I chagne env to Ubuntu 20.04

**This PR passed all tests**

as you know, in circle you test this project by ubuntu 20.04, so I think ubuntu 20.04 is acceptable for you

**Comment by soroshsabz** [comment]
@splitice I hope that the misunderstanding has been resolved

**Comment by soroshsabz** [comment]
> We can not choose to skip tests. Issues need to be diagnosed and fixed before any migration will proceed.
> 
> Currently I don't have the time for this.
> 
> It might be ipv6 related as you mentioned. Or it might be an API change/bug. Needs time.

@splitice Did you see my comment about not ignoring any test?

**Comment by soroshsabz** [comment]
@splitice Did you see my comment about not ignoring any test?

**Comment by splitice** [comment]
I'd like to actually investigate and tackle the issue. And will.

But very busy currently

**Comment by soroshsabz** [comment]
> I'd like to actually investigate and tackle the issue. And will.
> 
> But very busy currently

@splitice  you do not need to investigate anything in Ubuntu 20.04, After I resolve my mistake, there is no any issue exist yet. so I think you can approve this.

**Comment by soroshsabz** [comment]
@splitice 

Hi again,

Did you see my last comment?

**Comment by soroshsabz** [comment]
@splitice 

Hi again,

Did you see my last comment?

Any update?

**Comment by splitice** [comment]
I will get to this. I'd like to investigate the actual issue with newer ubuntu versions first before merging.

Should have time in November hopefully.

**Comment by splitice** [comment]
ubuntu latest uses nftables not iptables, thats why the tests fail

I think I've got all the test failures now. Including a couple fixes and an update to .NET 8

**Comment by splitice** [comment]
Latest master uses github actions

**Pull request closed without merging**
